"""Full QA regression suite for the DSA People & Culture static portal (HR Agent out of scope).
usage: python3 qa_suite.py <base_url> <admin_pw> <staff_pw>
"""
import asyncio, sys, os, json, re, time
from playwright.async_api import async_playwright

BASE, ADMIN_PW, STAFF_PW = sys.argv[1], sys.argv[2], sys.argv[3]
SP = os.path.dirname(os.path.abspath(__file__)); SHOTS = os.path.join(SP, "qa_shots"); os.makedirs(SHOTS, exist_ok=True)
RESULTS = []; SECTION = [""]
def sec(name): SECTION[0] = name; RESULTS.append(("SECTION", name, ""))
def ok(name, cond, info=""):
    RESULTS.append(("PASS" if cond else "FAIL", f"[{SECTION[0]}] {name}", str(info)[:300])); print(RESULTS[-1][0], RESULTS[-1][1], (RESULTS[-1][2] if not cond else ""), flush=True)

XSS = ['<script>window.__xss=1</script>', '<img src=x onerror="window.__xss=1">', '"><svg onload="window.__xss=1">']
IGNORED = ("fonts.googleapis", "fonts.gstatic", "ERR_TUNNEL_CONNECTION_FAILED", "ERR_NAME_NOT_RESOLVED")

class Env:
    def __init__(self, b): self.b = b; self.errors = []; self.dialogs = []
    async def ctx(self, w=1280, h=860, mobile=False, storage=None):
        c = await self.b.new_context(viewport={"width": w, "height": h}, is_mobile=mobile, has_touch=mobile, accept_downloads=True, storage_state=storage)
        p = await c.new_page(); self.watch(p); return c, p
    def watch(self, p):
        p.on("pageerror", lambda e: self.errors.append(("pageerror", str(e))))
        p.on("console", lambda m: m.type == "error" and not any(x in m.text for x in IGNORED) and self.errors.append(("console", m.text)))
        p.on("dialog", lambda d: (self.dialogs.append(d.message), asyncio.ensure_future(d.dismiss())))

async def login(p, role, pw, expect=True):
    await p.click(f'[data-role="{role}"]'); await p.fill("#pw", pw); await p.click("#signBtn")
    await p.wait_for_function("()=>!document.querySelector('#app').hidden || (document.querySelector('#pwErr').textContent.trim() && !document.querySelector('#signBtn').disabled)", timeout=20000)
    return not await p.locator("#app").is_hidden()

async def tab(p, t):
    await p.click(f'#nav [data-tab="{t}"]'); await p.wait_for_timeout(120)

async def tabs(p): return await p.eval_on_selector_all("#nav button[data-tab]", "els=>els.map(e=>e.dataset.tab)")
async def main_text(p): return await p.text_content("#main")
async def settle(p, ms=400): await p.wait_for_timeout(ms)

async def open_settings(p):
    if (p.viewport_size or {}).get("width", 1280) > 860 and await p.is_visible("#settingsBtn"): await p.click("#settingsBtn")
    else: await p.click("#userBtn"); await p.click('#menuPop button:has-text("Settings")')
    await p.wait_for_selector("#ac-ann")

async def set_access(p, ann=None, pol=None, dir=None, agent=None):
    await open_settings(p)
    for sel, v in (("#ac-ann", ann), ("#ac-pol", pol), ("#ac-dir", dir), ("#ac-agent", agent)):
        if v is not None: await (p.check(sel) if v else p.uncheck(sel))
    await p.click("#ac-save"); await settle(p, 200)
    await p.keyboard.press("Escape"); await settle(p, 150)

async def preview(p):
    await p.click("#userBtn"); await p.click('#menuPop button:has-text("Preview as staff")'); await settle(p, 300)
async def exit_preview(p):
    await p.click("#exitPreview"); await settle(p, 300)

async def save_dialog(p):
    await p.click('#dlgForm button[value="save"]'); await settle(p, 450)

async def overflow(p): return await p.evaluate("document.documentElement.scrollWidth - document.documentElement.clientWidth")

async def missing_icons(p):
    return await p.evaluate("""()=>[...document.querySelectorAll('use')].map(u=>u.getAttribute('href')).filter(h=>h&&h.startsWith('#')&&!document.getElementById(h.slice(1)))""")

async def run():
    async with async_playwright() as pw:
        b = await pw.chromium.launch()
        E = Env(b)

        # ================= 1. STARTUP =================
        sec("Startup")
        c, p = await E.ctx()
        r = await p.goto(BASE); ok("page loads (HTTP 200)", r.status == 200)
        ok("login gate visible, app hidden", await p.is_visible("#gate") and await p.locator("#app").is_hidden())
        ok("logo renders", await p.evaluate("document.querySelector('#gate img.logo').naturalWidth") > 0)
        ok("JS fallback hint hidden once script runs", await p.locator("#jsHint").is_hidden())
        ok("favicon is embedded", (await p.get_attribute('link[rel="icon"]', "href") or "").startswith("data:image/png"))
        ok("WhatsApp preview tags present", await p.get_attribute('meta[property="og:image"]', "content") == "https://people.drsalmanaesthetics.com/og.png")
        src_ = await p.content(); ok("no plaintext staff data in page source", not any(w in src_ for w in ["Saba Saeed", "5889045", "Rohail Khan", "Namra"]))
        ok("no horizontal overflow on login", await overflow(p) <= 0)
        await c.close()

        # ================= 2. AUTH =================
        sec("Authentication")
        c, p = await E.ctx()
        await p.goto(BASE)
        ok("password field focused on load", await p.evaluate("document.activeElement.id") == "pw")
        await p.click("#signBtn"); await settle(p, 200)
        ok("empty password does not sign in", await p.locator("#app").is_hidden())
        await p.fill("#pw", "   "); await p.evaluate("document.querySelector('#loginForm').requestSubmit()"); await settle(p, 200)
        ok("blank password shows message", "Enter the password" in await p.text_content("#pwErr"))
        ok("wrong staff password rejected", not await login(p, "staff", "nope-nope"))
        ok("staff error message", "not right" in await p.text_content("#pwErr"))
        ok("button re-enabled after failure", await p.is_enabled("#signBtn") and (await p.text_content("#signBtn")).strip() == "Sign in")
        ok("wrong admin password rejected", not await login(p, "admin", "nope-nope"))
        ok("admin error message", "admin password is not right" in await p.text_content("#pwErr"))
        ok("staff password cannot open admin", not await login(p, "admin", STAFF_PW))
        await p.click('[data-role="staff"]')
        ok("switching role clears error", (await p.text_content("#pwErr")).strip() == "")
        ok("role buttons expose aria-pressed", await p.get_attribute('[data-role="staff"]', "aria-pressed") == "true" and await p.get_attribute('[data-role="admin"]', "aria-pressed") == "false")
        await p.click('[data-role="admin"]'); ok("focus returns to password after role switch", await p.evaluate("document.activeElement.id") == "pw")
        # button disabled while authenticating
        await p.click('[data-role="staff"]'); await p.fill("#pw", STAFF_PW)
        await p.evaluate("document.querySelector('#loginForm').requestSubmit()")
        ok("sign-in button disabled while checking", await p.evaluate("document.querySelector('#signBtn').disabled"))
        await p.wait_for_selector("#app:not([hidden])")
        ok("staff signs in", True)
        ok("password field cleared after sign-in", await p.input_value("#pw") == "")
        await p.reload(); await p.wait_for_selector("#app:not([hidden])", timeout=10000)
        ok("session resumes after refresh", True)
        p2 = await c.new_page(); E.watch(p2); await p2.goto(BASE); await settle(p2, 800)
        ok("new tab asks for sign-in (session is per tab)", await p2.locator("#app").is_hidden())
        await p2.close()
        await p.click("#userBtn"); await p.click('#menuPop button:has-text("Sign out")'); await p.wait_for_selector("#gate:not([hidden])")
        ok("sign out returns to gate", await p.locator("#app").is_hidden())
        ok("sign out clears session storage", await p.evaluate("sessionStorage.getItem('dsa-po-session')") is None)
        ok("no protected data in DOM after sign out", (await p.text_content("#main")).strip() == "" and "Handbook" not in await p.inner_text("body"))
        await p.go_back(); await settle(p, 600)
        ok("Back after sign out does not restore screens", await p.locator("#app").is_hidden() or "about:blank" in p.url)
        await c.close()

        # ================= 3. RBAC =================
        sec("Role permissions")
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "admin", ADMIN_PW)
        t = await tabs(p); ok("admin navigation", t == ["overview", "announcements", "people", "policies", "documents", "agent"], t)
        ok("admin sees Settings and Quick add", await p.is_visible("#settingsBtn") and await p.is_visible("#quickAdd"))
        await p.click("#quickAdd"); items = await p.eval_on_selector_all("#menuPop [role=menuitem]", "e=>e.map(x=>x.textContent.trim())")
        ok("quick add menu", items == ["Add employee", "Post announcement", "Upload file", "Add document", "Add policy"], items)
        await p.keyboard.press("Escape"); await p.mouse.click(5, 5)
        for t_ in ["overview", "announcements", "people", "policies", "documents"]:
            await tab(p, t_); ok(f"admin view '{t_}' renders", len((await main_text(p)).strip()) > 50)
            mi = await missing_icons(p); ok(f"no missing icons on '{t_}'", not mi, mi)
        await c.close()

        c, p = await E.ctx(); await p.goto(BASE); await login(p, "staff", STAFF_PW)
        t = await tabs(p); ok("staff navigation (default access)", t == ["overview", "announcements", "policies", "documents", "agent"], t)
        await tab(p, "documents"); ok("staff: documents empty state when nothing shared", "No documents shared yet" in await main_text(p))
        ok("staff: Settings hidden", await p.locator("#settingsBtn").is_hidden())
        ok("staff: Quick add hidden", await p.locator("#quickAdd").is_hidden())
        await p.evaluate("document.querySelector('#quickAdd').click()"); await settle(p, 200)
        ok("staff: forced Quick add click does nothing", await p.locator("#menuPop").count() == 0)
        await p.evaluate("document.querySelector('#settingsBtn').click()"); await settle(p, 200)
        ok("staff: forced Settings click does nothing", not await p.evaluate("document.querySelector('#dlg').open"))
        await p.set_input_files("#filePick", files=[{"name": "x.txt", "mimeType": "text/plain", "buffer": b"x"}]); await settle(p, 200)
        ok("staff: forced file upload does nothing", not await p.evaluate("document.querySelector('#dlg').open"))
        await p.evaluate("location.hash='#documents'"); await p.reload(); await p.wait_for_selector("#app:not([hidden])"); await settle(p)
        ok("staff: #documents opens the staff documents view, not the admin library", await p.text_content("#pageTitle") == "Documents" and await p.locator("#drop,[data-dmode],[data-del],[data-vis]").count() == 0)
        await p.evaluate("location.hash='#people'"); await p.reload(); await p.wait_for_selector("#app:not([hidden])"); await settle(p)
        ok("staff: #people URL blocked when directory is off", "Team Directory" != await p.text_content("#pageTitle"))
        globals_ = await p.evaluate("['S','KEYS','ROLE','isAdmin','openForm','openSettings','PAGE_VAULT'].filter(k=>k in window)")
        ok("staff: app internals not exposed on window", globals_ == [], globals_)
        ss = await p.evaluate("JSON.parse(sessionStorage.getItem('dsa-po-session'))")
        ok("staff session holds no admin key", ss["role"] == "staff" and not ss.get("ka"))
        await p.evaluate("const s=JSON.parse(sessionStorage.getItem('dsa-po-session')); s.role='admin'; sessionStorage.setItem('dsa-po-session',JSON.stringify(s))")
        await p.reload(); await settle(p, 1200)
        ok("staff: forging role=admin in session is refused", await p.locator("#app").is_hidden())
        ok("forged session cleared", await p.evaluate("sessionStorage.getItem('dsa-po-session')") is None)
        await login(p, "staff", STAFF_PW)
        await tab(p, "announcements"); ok("staff: no announcement admin controls", await p.locator("[data-edit],[data-pin],[data-vis],[data-del],[data-new]").count() == 0)
        await tab(p, "policies"); ok("staff: no policy admin controls", await p.locator("[data-edit],[data-vis],[data-del],[data-new]").count() == 0)
        body = await p.inner_text("body")
        ok("staff: no phone numbers/emails/notes anywhere", not re.search(r"\+92|@drsalman|@gmail|5889045", body))
        ok("staff: no localStorage writes", await p.evaluate("localStorage.getItem('dsa-people-vault-v1')") is None)
        await c.close()

        # ================= 4. STAFF ACCESS =================
        sec("Staff access")
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "admin", ADMIN_PW)
        await tab(p, "people"); before_people = await p.text_content('#nav [data-tab="people"] .count')
        before_counts = await p.eval_on_selector_all("#nav .count", "e=>e.map(x=>x.textContent)")
        combos = [(1,1,1),(1,0,0),(0,1,0),(0,0,1),(0,0,0),(1,1,0),(0,1,1),(1,0,1)]
        for a_, p_, d_ in combos:
            await set_access(p, bool(a_), bool(p_), bool(d_))
            await preview(p)
            t = await tabs(p)
            exp = ["overview"] + (["announcements"] if a_ else []) + (["policies"] if p_ else []) + ["documents"] + (["people"] if d_ else []) + ["agent"]
            ok(f"preview tabs ann={a_} pol={p_} dir={d_}", t == exp, t)
            home = await main_text(p)
            ok(f"home respects access ann={a_} pol={p_}", (("Latest announcements" in home) == bool(a_)) and (("Open library" in home) == bool(p_)))
            ok(f"preview banner shown", await p.is_visible(".preview-bar"))
            ok("preview hides Settings / Quick add", await p.locator("#settingsBtn").is_hidden() and await p.locator("#quickAdd").is_hidden())
            if d_:
                await tab(p, "people"); txt = await main_text(p)
                ok("directory shows names, no contact data", "Saba Saeed" in txt and "5889045" not in txt and "Former" not in txt)
            await exit_preview(p)
        after_counts = await p.eval_on_selector_all("#nav .count", "e=>e.map(x=>x.textContent)")
        ok("admin data unchanged after previews", before_counts == after_counts, (before_counts, after_counts))
        ok("admin tabs restored after preview", await tabs(p) == ["overview", "announcements", "people", "policies", "documents", "agent"])
        await p.reload(); await p.wait_for_selector("#app:not([hidden])"); await open_settings(p)
        ok("access settings persist after refresh", await p.is_checked("#ac-ann") and not await p.is_checked("#ac-pol") and await p.is_checked("#ac-dir"))
        await p.keyboard.press("Escape")
        await set_access(p, True, True, False)
        await c.close()

        # ================= 5/6. PEOPLE =================
        sec("People directory")
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "admin", ADMIN_PW); await tab(p, "people")
        rows = lambda: p.locator("#main tbody tr")
        n_all = await rows().count(); ok("table lists current staff", n_all >= 25, n_all)
        await p.click('[data-view="cards"]'); ok("card view", await p.locator(".pcard").count() == n_all)
        for _ in range(3): await p.click('[data-view="table"]'); await p.click('[data-view="cards"]')
        await p.click('[data-view="table"]'); ok("repeated view switching stable", await rows().count() == n_all)
        await p.fill("#pq", "saba"); await settle(p, 150); ok("search by name (case-insensitive)", await rows().count() == 1)
        ok("search keeps focus while typing", await p.evaluate("document.activeElement.id") == "pq")
        await p.fill("#pq", "zzzz-none"); await settle(p, 150); ok("zero-result search message", "No one matches" in await main_text(p))
        await p.fill("#pq", ""); await settle(p, 150)
        await p.select_option("#ps", "Former"); n_former = await rows().count(); ok("status filter Former", n_former == 2, n_former)
        await p.select_option("#ps", ""); ok("status filter Everyone", await rows().count() == n_all + n_former)
        await p.select_option("#ps", "Active")
        depts = await p.eval_on_selector_all("#pd option", "e=>e.map(x=>x.value).filter(Boolean)")
        await p.select_option("#pd", depts[0]); n_d = await rows().count(); ok("department filter", 0 < n_d < n_all, n_d)
        br = await p.eval_on_selector_all("#pb option", "e=>e.map(x=>x.value).filter(Boolean)")
        if br:
            await p.select_option("#pb", br[0]); ok("combined department+branch filter", await rows().count() <= n_d)
        await p.select_option("#pd", ""); await p.select_option("#pb", ""); ok("clearing filters restores list", await rows().count() == n_all)
        # create QA employee
        await p.click('[data-new="employee"]'); await p.wait_for_selector("#fe-name")
        await p.fill("#fe-name", "  QA Test Employee  "); await p.fill("#fe-role", "QA Analyst"); await p.fill("#fe-dept", "Operations")
        await p.select_option("#fe-branch", "Islamabad"); await p.fill("#fe-phone", "+92 300 1234567"); await p.fill("#fe-email", "qa.test@example.com")
        await p.fill("#fe-notes", "Line one\nLine two"); await p.fill("#fe-manager", "QA Manager")
        await p.dblclick('#dlgForm button[value="save"]'); await settle(p)
        await p.fill("#pq", "QA Test Employee"); await settle(p, 150)
        ok("QA employee created once (double-click safe)", await rows().count() == 1, await rows().count())
        ok("name trimmed", await p.locator("#main tbody tr .n").first.text_content() == "QA Test Employee")
        await rows().first.click(); await p.wait_for_selector(".dossier-top")
        dtxt = await p.inner_text("#dlg")
        ok("profile shows details", all(x in dtxt for x in ["QA Test Employee", "QA Analyst", "Operations", "Islamabad", "+92 300 1234567", "qa.test@example.com", "QA Manager"]))
        await p.click('[data-ptab="notes"]'); ok("multi-line notes", "Line one\nLine two" in await p.inner_text("#dlg"))
        await p.click("#pEdit"); await p.wait_for_selector("#fe-role")
        await p.fill("#fe-role", "Senior QA Analyst with a deliberately long role title for layout testing"); await save_dialog(p)
        ok("edit updates immediately", "Senior QA Analyst" in await main_text(p))
        await p.reload(); await p.wait_for_selector("#app:not([hidden])"); await tab(p, "people"); await p.fill("#pq", "QA Test"); await settle(p, 150)
        await rows().first.click(); await p.wait_for_selector(".dossier-top"); dtxt = await p.inner_text("#dlg")
        ok("edit persists after refresh, other fields intact", "Senior QA Analyst" in dtxt and "+92 300 1234567" in dtxt and "qa.test@example.com" in dtxt)
        await p.keyboard.press("Escape")
        # Enter key inside a form must save, not cancel
        await p.click('[data-new="employee"]'); await p.fill("#fe-name", "QA Enter Key"); await p.press("#fe-name", "Enter"); await settle(p)
        await p.fill("#pq", "QA Enter Key"); await settle(p, 150)
        ok("Enter in a form field saves the form", await rows().count() == 1)
        # special characters & long name
        await p.click('[data-new="employee"]'); await p.fill("#fe-name", "Ayşe O'Brien-Zaheer \"QA\" ابن " + "Long" * 12); await save_dialog(p)
        await p.fill("#pq", "O'Brien"); await settle(p, 150); ok("special characters and Unicode saved", await rows().count() == 1)
        ok("long name does not overflow page", await overflow(p) <= 0)
        await p.click("#userBtn"); await p.click('#menuPop button:has-text("Sign out")'); await p.wait_for_selector("#gate:not([hidden])")
        await login(p, "admin", ADMIN_PW); await tab(p, "people"); await p.fill("#pq", "QA Test Employee"); await settle(p, 150)
        ok("QA employee survives sign out / sign in", await rows().count() == 1)
        ok("employees have no delete (set status to Former instead)", await p.locator('[data-del^="employees"]').count() == 0)
        await c.close()

        # ================= 8. ANNOUNCEMENTS =================
        sec("Announcements")
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "admin", ADMIN_PW); await tab(p, "announcements")
        n0 = await p.locator(".feed .ann").count()
        await p.click('[data-new="announcement"]'); await p.fill("#fa-title", "QA TEST ANNOUNCEMENT"); await p.select_option("#fa-cat", "Event")
        await p.select_option("#fa-aud", "Islamabad"); await p.fill("#fa-date", "2026-09-01"); await p.fill("#fa-body", "QA body line 1\nQA body line 2"); await p.check("#fa-pin")
        await p.dblclick('#dlgForm button[value="save"]'); await settle(p)
        ok("announcement created once", await p.locator(".ann h3", has_text="QA TEST ANNOUNCEMENT").count() == 1)
        first = await p.locator(".feed .ann h3").first.text_content(); ok("pinned announcement sorted first", "QA TEST" in first or await p.locator(".feed .ann.pinned").count() >= 2)
        await p.fill("#aq", "qa body"); await settle(p, 150); ok("search finds body text", await p.locator(".feed .ann").count() == 1)
        await p.fill("#aq", ""); await p.select_option("#ac", "Event"); tops_ = await p.locator(".feed .ann .ann-top").all_text_contents(); ok("category filter", len(tops_) >= 1 and all("Event" in t for t in tops_))
        await p.select_option("#ac", "")
        # expired
        await p.click('[data-new="announcement"]'); await p.fill("#fa-title", "QA EXPIRED NOTICE"); await p.fill("#fa-body", "old"); await p.fill("#fa-exp", "2026-01-01"); await save_dialog(p)
        ok("expired announcement hidden from Current", await p.locator(".ann h3", has_text="QA EXPIRED").count() == 0)
        await p.select_option("#as", "archived"); ok("expired announcement under Past", await p.locator(".ann h3", has_text="QA EXPIRED").count() == 1)
        await p.select_option("#as", "current")
        # visibility
        await preview(p); await tab(p, "announcements"); ok("QA announcement visible to staff", await p.locator(".ann h3", has_text="QA TEST ANNOUNCEMENT").count() == 1)
        await exit_preview(p); await tab(p, "announcements")
        await p.locator('.ann:has-text("QA TEST ANNOUNCEMENT") [data-vis]').click(); await settle(p, 200)
        ok("hidden announcement tagged Admins only", await p.locator('.ann:has-text("QA TEST ANNOUNCEMENT") .pill.lock').count() == 1)
        await preview(p); await tab(p, "announcements"); ok("hidden announcement gone for staff", await p.locator(".ann h3", has_text="QA TEST ANNOUNCEMENT").count() == 0)
        await exit_preview(p); await tab(p, "announcements")
        await p.locator('.ann:has-text("QA TEST ANNOUNCEMENT") [data-edit]').click(); await p.wait_for_selector("#fa-title")
        ok("edit form reflects hidden state", not await p.is_checked("#fa-staff"))
        await p.fill("#fa-title", "QA TEST ANNOUNCEMENT EDITED"); await save_dialog(p)
        await p.reload(); await p.wait_for_selector("#app:not([hidden])"); await tab(p, "announcements")
        ok("announcement edit persists after refresh", await p.locator(".ann h3", has_text="QA TEST ANNOUNCEMENT EDITED").count() == 1)
        # delete: double-click must not delete
        btn = p.locator('.ann:has-text("QA TEST ANNOUNCEMENT EDITED") [data-del]')
        await btn.dblclick(); await settle(p, 200)
        ok("double-click on delete does not delete", await p.locator(".ann h3", has_text="QA TEST ANNOUNCEMENT EDITED").count() == 1)
        await settle(p, 300); await btn.click(); await settle(p, 300)
        ok("deliberate confirm deletes", await p.locator(".ann h3", has_text="QA TEST ANNOUNCEMENT EDITED").count() == 0)
        await p.locator(".feed .ann").first.click(); await p.wait_for_selector("#dlg[open]")
        ok("announcement opens in dialog", await p.locator("#dlg .ann").count() == 1)
        await p.click('#dlg [data-close]'); ok("dialog closes with X", not await p.evaluate("document.querySelector('#dlg').open"))
        await c.close()

        # ================= 9. POLICIES =================
        sec("Policies")
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "admin", ADMIN_PW); await tab(p, "policies")
        await p.click('[data-pol="employee-handbook"]'); await settle(p, 150); ok("handbook renders long text", len(await p.inner_text(".article .body")) > 5000)
        ok("policy facts shown", "Effective" in await p.inner_text(".article .facts"))
        await p.click('[data-new="policy"]'); await p.fill("#fp-title", "QA TEST POLICY"); await p.fill("#fp-code", "QA-001"); await p.fill("#fp-eff", "1 Oct 2026")
        await p.fill("#fp-cat", "QA"); await p.fill("#fp-body", "QA policy body.\nSecond line."); await p.dblclick('#dlgForm button[value="save"]'); await settle(p)
        ok("policy created once", await p.locator(".kb-item", has_text="QA TEST POLICY").count() == 1)
        await p.fill("#polq", "qa-001"); await settle(p, 150); ok("search by code", await p.locator(".kb-item").count() == 1)
        await p.fill("#polq", ""); await settle(p, 150)
        await p.locator(".kb-item", has_text="QA TEST POLICY").click(); await settle(p, 150)
        ok("policy opens", (await p.text_content(".article h2")) == "QA TEST POLICY")
        await p.click('.article [data-edit]'); await p.fill("#fp-body", "QA policy body edited."); await save_dialog(p)
        ok("policy edit shows", "edited" in await p.inner_text(".article .body"))
        await p.click('.article [data-vis]'); await settle(p, 200)
        await preview(p); await tab(p, "policies"); ok("hidden policy not visible to staff", await p.locator(".kb-item", has_text="QA TEST POLICY").count() == 0)
        await exit_preview(p)
        await p.reload(); await p.wait_for_selector("#app:not([hidden])"); await tab(p, "policies")
        ok("policy persists after refresh (with hidden state)", await p.locator(".kb-item", has_text="QA TEST POLICY").count() == 1 and "Admins only" in await p.locator(".kb-item", has_text="QA TEST POLICY").text_content())
        await p.locator(".kb-item", has_text="QA TEST POLICY").click(); await settle(p, 150)
        d = p.locator('.article [data-del]'); await d.dblclick(); await settle(p, 150)
        ok("policy double-click delete blocked", await p.locator(".kb-item", has_text="QA TEST POLICY").count() == 1)
        await settle(p, 300); await d.click(); await settle(p, 300)
        ok("policy delete works", await p.locator(".kb-item", has_text="QA TEST POLICY").count() == 0)
        ok("library falls back to another policy", (await p.text_content(".article h2")) != "")
        await c.close()

        # ================= 10. DOCUMENTS =================
        sec("Documents")
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "admin", ADMIN_PW); await tab(p, "documents")
        pdf = b"%PDF-1.4\n1 0 obj<<>>endobj\ntrailer<<>>\n%%EOF"
        png = bytes.fromhex("89504E470D0A1A0A0000000D49484452000000010000000108060000001F15C4890000000D4944415478DA63F8CFC0F01F0005000201F5D2A6A40000000049454E44AE426082")
        files = [
            {"name": "qa-contract.pdf", "mimeType": "application/pdf", "buffer": pdf},
            {"name": "qa-photo.png", "mimeType": "image/png", "buffer": png},
            {"name": "qa-photo.jpg", "mimeType": "image/jpeg", "buffer": b"\xff\xd8\xff\xe0qa-jpg"},
            {"name": "qa-letter.docx", "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "buffer": b"PK\x03\x04qa-docx"},
            {"name": "qa-notes.txt", "mimeType": "text/plain", "buffer": b"QA-SECRET-TEXT"},
            {"name": "qa-" + "very-long-file-name-" * 8 + ".txt", "mimeType": "text/plain", "buffer": b"long"},
            {"name": "qa-odd.xyz", "mimeType": "", "buffer": b"odd"},
            {"name": "qa-empty.txt", "mimeType": "text/plain", "buffer": b""},
        ]
        await p.set_input_files("#filePick", files=files); await p.wait_for_selector("#ff-emp")
        await p.select_option("#ff-cat", "Contract"); await p.fill("#ff-note", "QA batch")
        await p.dblclick('#dlgForm button[value="save"]'); await settle(p, 1500)
        names = await p.locator("#main tbody .fname .n").all_text_contents()
        ok("7 non-empty files uploaded once each", sum(1 for n in names if n.startswith("qa-")) == 7, names)
        ok("empty file rejected with feedback", "qa-empty.txt" not in names)
        await p.set_input_files("#filePick", files=[files[4]]); await p.wait_for_selector("#ff-emp"); await save_dialog(p); await settle(p, 800)
        ok("duplicate filename allowed as separate file", (await p.locator("#main tbody .fname .n").all_text_contents()).count("qa-notes.txt") == 2)
        await p.fill("#fq", "QA batch"); await settle(p, 150); ok("file search by note", await p.locator("#main tbody tr").count() == 7)
        await p.fill("#fq", ""); await p.select_option("#fc", "Contract"); ok("file category filter", await p.locator("#main tbody tr").count() == 8)
        await p.select_option("#fc", "")
        row = p.locator('#main tbody tr:has-text("qa-contract.pdf")')
        async with p.expect_download() as dl: await row.locator("[data-dl]").click()
        ok("PDF downloads intact", open(await (await dl.value).path(), "rb").read() == pdf)
        async with p.expect_popup() as pop: await p.locator('#main tbody tr:has-text("qa-photo.png") [data-file]').click()
        pp_ = await pop.value; await pp_.wait_for_load_state(); ok("file opens in a new tab (image preview)", pp_.url.startswith("blob:"), pp_.url)
        await (await pop.value).close()
        row = p.locator('#main tbody tr:has-text("qa-photo.png")')
        async with p.expect_download() as dl: await row.locator("[data-dl]").click()
        ok("PNG downloads intact", open(await (await dl.value).path(), "rb").read() == png)
        big = os.urandom(6 * 1024 * 1024)
        await p.set_input_files("#filePick", files=[{"name": "qa-big.bin", "mimeType": "application/octet-stream", "buffer": big}]); await p.wait_for_selector("#ff-emp")
        await p.select_option("#ff-emp", index=1); await save_dialog(p); await settle(p, 2500)
        row = p.locator('#main tbody tr:has-text("qa-big.bin")')
        async with p.expect_download() as dl: await row.locator("[data-dl]").click()
        ok("6 MB file round-trips through encryption", open(await (await dl.value).path(), "rb").read() == big)
        ok("file linked to employee", (await row.locator("td").nth(2).text_content()).strip() not in ("", "—"))
        raw = await p.evaluate("""async()=>{ const db=await new Promise(r=>{const q=indexedDB.open('dsa-people-vault-files',1); q.onsuccess=()=>r(q.result);});
            return await new Promise(r=>{ const s=db.transaction('blobs').objectStore('blobs'); const a=s.getAll(); a.onsuccess=()=>r(JSON.stringify(a.result.map(x=>({k:Object.keys(x),t:typeof x.ct, plain:atob(x.ct).includes('QA-SECRET')})))); }); }""")
        ok("files stored encrypted in IndexedDB", '"plain":true' not in raw and '"ct"' in raw, raw[:200])
        await p.reload(); await p.wait_for_selector("#app:not([hidden])"); await tab(p, "documents")
        ok("files persist after refresh", await p.locator('#main tbody tr:has-text("qa-notes.txt")').count() == 2)
        # missing blob handling
        fid = await p.locator('#main tbody tr:has-text("qa-odd.xyz") [data-dl]').get_attribute("data-dl")
        await p.evaluate(f"""async()=>{{ const db=await new Promise(r=>{{const q=indexedDB.open('dsa-people-vault-files',1); q.onsuccess=()=>r(q.result);}}); await new Promise(r=>{{ const t=db.transaction('blobs','readwrite'); t.objectStore('blobs').delete('{fid}'); t.oncomplete=r; }}); }}""")
        await p.locator('#main tbody tr:has-text("qa-odd.xyz") [data-dl]').click(); await settle(p, 400)
        ok("missing file gives understandable message", "not stored in this browser" in (await p.text_content("#toast") or ""))
        # remove file with confirm
        d = p.locator('#main tbody tr:has-text("qa-odd.xyz") [data-del]'); await d.dblclick(); await settle(p, 150)
        ok("file remove: double-click blocked", await p.locator('#main tbody tr:has-text("qa-odd.xyz")').count() == 1)
        await settle(p, 300); await d.click(); await settle(p, 300)
        ok("file remove works", await p.locator('#main tbody tr:has-text("qa-odd.xyz")').count() == 0)
        # letters
        await p.click('[data-dmode="letters"]'); await p.click('[data-new="document"]'); await p.fill("#fd-title", "QA TEST LETTER")
        await p.select_option("#fd-kind", "Memo"); await p.select_option("#fd-emp", index=2); await p.fill("#fd-body", "Ref DSA-HR-MEMO-2026-001\nBody")
        await p.dblclick('#dlgForm button[value="save"]'); await settle(p)
        ok("letter created once", await p.locator('#main tbody tr:has-text("QA TEST LETTER")').count() == 1)
        ok("letter reference detected", "DSA-HR-MEMO-2026-001" in await main_text(p))
        await p.fill("#dq", "qa test letter"); await settle(p, 150); ok("letter search", await p.locator("#main tbody tr").count() == 1)
        await p.locator('#main tbody tr:has-text("QA TEST LETTER")').click(); await p.wait_for_selector("#docText")
        ok("letter opens with body", "Body" in await p.inner_text("#docText")); await p.keyboard.press("Escape")
        await p.reload(); await p.wait_for_selector("#app:not([hidden])"); await tab(p, "documents"); await p.click('[data-dmode="letters"]')
        ok("letter persists after refresh", await p.locator('#main tbody tr:has-text("QA TEST LETTER")').count() == 1)
        await p.locator('#main tbody tr:has-text("QA TEST LETTER") [data-menu]').click(); await p.click('#menuPop button:has-text("Delete")'); await settle(p, 200)
        ok("menu delete asks for confirmation", await p.evaluate("document.querySelector('#dlg').open") and await p.locator('#main tbody tr:has-text("QA TEST LETTER")').count() == 1)
        await settle(p, 300); await p.click("#docDel"); await settle(p, 300)
        ok("letter deleted after confirm", await p.locator('#main tbody tr:has-text("QA TEST LETTER")').count() == 0)
        await c.close()

        # ================= 11. STORAGE =================
        sec("Storage & persistence")
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "admin", ADMIN_PW)
        await tab(p, "announcements"); await p.click('[data-new="announcement"]'); await p.fill("#fa-title", "QA PERSIST CHECK"); await p.fill("#fa-body", "x"); await save_dialog(p)
        st = await p.evaluate("localStorage.getItem('dsa-people-vault-v1')")
        ok("local admin changes stored encrypted", st and "QA PERSIST" not in st and "Saba" not in st and '"adm"' in st)
        ok("old plaintext store removed", await p.evaluate("localStorage.getItem('dsa-people-office-v1')") is None)
        state = await c.storage_state()
        await c.close()
        c, p = await E.ctx(storage=state); await p.goto(BASE)
        ok("closing the browser signs you out", await p.locator("#app").is_hidden())
        await login(p, "admin", ADMIN_PW); await tab(p, "announcements")
        ok("changes survive a browser restart", await p.locator(".ann h3", has_text="QA PERSIST CHECK").count() == 1)
        await p.evaluate("localStorage.setItem('dsa-people-vault-v1','{not json')")
        await p.click("#userBtn"); await p.click('#menuPop button:has-text("Sign out")'); await p.wait_for_selector("#gate:not([hidden])")
        ok("corrupted local store: admin still signs in", await login(p, "admin", ADMIN_PW))
        await p.evaluate("sessionStorage.setItem('dsa-po-session','{\"role\":\"admin\",\"ke\":\"%%%\"}')"); await p.reload(); await settle(p, 800)
        ok("corrupted session: safe fallback to sign-in", await p.locator("#app").is_hidden() and await p.is_visible("#pw"))
        await c.close()

        # ================= 12/13. PASSWORDS & PUBLISH =================
        sec("Publish & passwords")
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "admin", ADMIN_PW)
        await set_access(p, True, True, True)
        await tab(p, "policies"); await p.click('[data-new="policy"]'); await p.fill("#fp-title", "QA EXPORT POLICY"); await p.fill("#fp-body", "x"); await save_dialog(p)
        await tab(p, "documents"); await p.set_input_files("#filePick", files=[{"name": "qa-export.txt", "mimeType": "text/plain", "buffer": b"EXPORT-OK"}]); await p.wait_for_selector("#ff-emp"); await save_dialog(p); await settle(p, 800)
        await p.set_input_files("#filePick", files=[{"name": "qa-shared-form.txt", "mimeType": "text/plain", "buffer": b"SHARED-FORM"}]); await p.wait_for_selector("#ff-staff")
        ok("upload: staff checkbox unticked by default", not await p.is_checked("#ff-staff"))
        await p.select_option("#ff-emp", index=3); await p.check("#ff-staff"); await save_dialog(p); await settle(p, 800)
        ok("shared file marked in admin table", await p.locator('#main tbody tr:has-text("qa-shared-form.txt") .pill.ok').count() == 1)
        ok("private file not marked", await p.locator('#main tbody tr:has-text("qa-export.txt") .pill.ok').count() == 0)
        await p.locator('#main tbody tr:has-text("qa-export.txt") [data-vis]').click(); await settle(p, 300)
        ok("people-icon toggle shares a file", await p.locator('#main tbody tr:has-text("qa-export.txt") .pill.ok').count() == 1)
        await p.locator('#main tbody tr:has-text("qa-export.txt") [data-vis]').click(); await settle(p, 300)
        ok("toggle again hides it", await p.locator('#main tbody tr:has-text("qa-export.txt") .pill.ok').count() == 0)
        await p.click('[data-dmode="letters"]'); await p.click('[data-new="document"]'); await p.fill("#fd-title", "QA SHARED LETTER"); await p.fill("#fd-body", "Shared body"); await p.check("#fd-staff"); await save_dialog(p)
        await p.click('[data-new="document"]'); await p.fill("#fd-title", "QA PRIVATE LETTER"); await p.fill("#fd-body", "Private body"); await save_dialog(p)
        ok("letters: shared one marked", await p.locator('#main tbody tr:has-text("QA SHARED LETTER") .pill.ok').count() == 1 and await p.locator('#main tbody tr:has-text("QA PRIVATE LETTER") .pill.ok').count() == 0)
        await preview(p); await tab(p, "documents"); txt_ = await main_text(p)
        ok("preview: staff see only shared documents", "qa-shared-form.txt" in txt_ and "QA SHARED LETTER" in txt_ and "qa-export.txt" not in txt_ and "QA PRIVATE LETTER" not in txt_)
        async with p.expect_download() as dl: await p.locator('#main tbody tr:has-text("qa-shared-form.txt") [data-dl]').click()
        ok("preview: shared file downloads", open(await (await dl.value).path(), "rb").read() == b"SHARED-FORM")
        await exit_preview(p)
        await open_settings(p)
        async with p.expect_download() as dl: await p.click("#st-copy")
        d = await dl.value; ok("download named index.html", d.suggested_filename == "index.html")
        exp = os.path.join(SP, "out_qa", "export1.html"); os.makedirs(os.path.dirname(exp), exist_ok=True); await d.save_as(exp)
        html = open(exp).read()
        mv_ = re.search(r'<script id="vault" type="application/json">(\{.*?\})</script>', html, re.S)
        ok("export is well-formed (valid vault JSON, closes html)", bool(mv_) and json.loads(mv_.group(1)).get("v") == 1 and html.rstrip().endswith("</html>") and "__VAULT__" not in html, html[-40:])
        ok("export contains no plaintext", not any(w in html for w in ["QA EXPORT POLICY", "EXPORT-OK", "Saba Saeed"]))
        # password validation
        async def pwchange(cur, na, ns):
            await p.fill("#pw-cur", cur); await p.fill("#pw-admin", na); await p.fill("#pw-staff", ns); await p.click("#pw-save")
            await p.wait_for_function("()=>!/Checking/.test(document.querySelector('#pw-msg').textContent)", timeout=20000)
            return await p.text_content("#pw-msg")
        ok("empty new passwords rejected", "at least one" in await pwchange(ADMIN_PW, "", ""))
        ok("empty current password rejected", "not right" in await pwchange("", "QaAdmin-1234", ""))
        ok("wrong current password rejected", "not right" in await pwchange("wrong", "QaAdmin-1234", ""))
        ok("short password rejected", "8 characters" in await pwchange(ADMIN_PW, "short", ""))
        ok("same admin/staff password rejected", "different" in await pwchange(ADMIN_PW, "SamePass-123", "samepass-123"))
        ok("staff-only change", "New passwords saved" in await pwchange(ADMIN_PW, "", "QaStaff-5678"))
        ok("admin-only change", "New passwords saved" in await pwchange(ADMIN_PW, "QaAdmin-1234", ""))
        async with p.expect_download() as dl: await p.click("#st-copy")
        exp2 = os.path.join(SP, "out_qa", "export2.html"); await (await dl.value).save_as(exp2)
        await c.close()
        import shutil; shutil.copy(exp, os.path.join(SP, "out10", "qa-export1.html")); shutil.copy(exp2, os.path.join(SP, "out10", "qa-export2.html"))
        c, p = await E.ctx(); await p.goto(BASE + "qa-export1.html")
        ok("export 1: staff sign-in works", await login(p, "staff", STAFF_PW))
        t = await tabs(p); ok("export 1: staff access preserved (directory on)", "people" in t, t)
        await tab(p, "policies"); ok("export 1: QA policy visible to staff", await p.locator(".kb-item", has_text="QA EXPORT POLICY").count() == 1)
        await tab(p, "documents"); txt_ = await main_text(p)
        ok("export 1: staff see shared file and letter only", "qa-shared-form.txt" in txt_ and "QA SHARED LETTER" in txt_ and "qa-export.txt" not in txt_ and "QA PRIVATE LETTER" not in txt_)
        ok("export 1: staff don't see who a shared file belongs to", await p.locator("#main th", has_text="Employee").count() == 0)
        async with p.expect_download() as dl: await p.locator('#main tbody tr:has-text("qa-shared-form.txt") [data-dl]').click()
        ok("export 1: staff can download a shared file", open(await (await dl.value).path(), "rb").read() == b"SHARED-FORM")
        await p.locator('#main tbody tr:has-text("QA SHARED LETTER")').click(); await p.wait_for_selector("#docText")
        ok("export 1: staff can read a shared letter, no delete", "Shared body" in await p.inner_text("#docText") and await p.locator("#docDel").count() == 0)
        await p.keyboard.press("Escape")
        await p.click("#searchBtn"); await p.fill("#gq", "QA"); await settle(p, 200); g_ = await p.inner_text("#gres")
        ok("export 1: staff search finds shared docs only", "QA SHARED LETTER" in g_ and "QA PRIVATE LETTER" not in g_ and "qa-export.txt" not in g_)
        await p.keyboard.press("Escape")
        await c.close()
        c, p = await E.ctx(); await p.goto(BASE + "qa-export1.html"); await login(p, "admin", ADMIN_PW)
        await tab(p, "people"); ok("export 1: employees present", await p.locator("#main tbody tr").count() >= 25)
        await tab(p, "announcements"); ok("export 1: announcements present", await p.locator(".feed .ann").count() >= 3)
        await tab(p, "documents"); row = p.locator('#main tbody tr:has-text("qa-export.txt")')
        async with p.expect_download() as dl: await row.locator("[data-dl]").click()
        ok("export 1: uploaded file travels and decrypts", open(await (await dl.value).path(), "rb").read() == b"EXPORT-OK")
        await c.close()
        c, p = await E.ctx(); await p.goto(BASE + "qa-export2.html")
        ok("export 2: old admin password refused", not await login(p, "admin", ADMIN_PW))
        ok("export 2: old staff password refused", not await login(p, "staff", STAFF_PW))
        ok("export 2: new staff password works", await login(p, "staff", "QaStaff-5678"))
        await c.close()
        c, p = await E.ctx(); await p.goto(BASE + "qa-export2.html")
        ok("export 2: new admin password works", await login(p, "admin", "QaAdmin-1234"))
        await tab(p, "documents"); row = p.locator('#main tbody tr:has-text("qa-export.txt")')
        async with p.expect_download() as dl: await row.locator("[data-dl]").click()
        ok("export 2: data intact after key change", open(await (await dl.value).path(), "rb").read() == b"EXPORT-OK")
        await c.close()
        # discard local changes in a disposable copy
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "admin", ADMIN_PW)
        await tab(p, "announcements"); await p.click('[data-new="announcement"]'); await p.fill("#fa-title", "QA DISCARD ME"); await p.fill("#fa-body", "x"); await save_dialog(p)
        await open_settings(p); await p.dblclick("#st-reset"); await settle(p, 300)
        ok("discard needs a deliberate second click", await p.is_visible("#app"))
        await settle(p, 300); await p.click("#st-reset"); await p.wait_for_selector("#gate:not([hidden])")
        await login(p, "admin", ADMIN_PW); await tab(p, "announcements")
        ok("discard removes local changes", await p.locator(".ann h3", has_text="QA DISCARD ME").count() == 0)
        await c.close()

        # ================= 14. SEARCH =================
        sec("Global search")
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "admin", ADMIN_PW)
        await p.keyboard.press("Control+k"); await p.wait_for_selector("#gq")
        ok("Ctrl+K opens search", True)
        async def q(text):
            await p.fill("#gq", text); await settle(p, 150)
            return await p.eval_on_selector_all("#gres .sgroup", "e=>e.map(x=>x.textContent)")
        ok("finds employee (partial, lowercase)", "Employees" in await q("sab"))
        ok("finds policy", "Policies" in await q("HANDBOOK"))
        ok("finds announcement", "Announcements" in await q("hadir"))
        ok("special characters do not break search", (await q("(.*+?[")) is not None and await p.locator("#gres").count() == 1)
        await q("zzzzqqq"); ok("no-results message", "Nothing matches" in await p.inner_text("#gres"))
        await q("a"); await p.keyboard.press("ArrowDown"); await p.keyboard.press("ArrowDown"); await p.keyboard.press("ArrowUp")
        ok("arrow keys move selection", await p.locator("#gres .sres.on").count() == 1)
        await p.keyboard.press("Enter"); await settle(p, 300); ok("Enter opens result", await p.locator("#searchPop").count() == 0)
        await p.keyboard.press("Escape")
        await p.keyboard.press("Control+k"); await p.keyboard.press("Escape"); ok("Escape closes search", await p.locator("#searchPop").count() == 0)
        await c.close()
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "staff", STAFF_PW)
        await p.click("#searchBtn"); await p.fill("#gq", "a"); await settle(p, 150)
        groups = await p.eval_on_selector_all("#gres .sgroup", "e=>e.map(x=>x.textContent)")
        ok("staff search only covers shared content", set(groups) <= {"Announcements", "Policies", "Team"}, groups)
        await p.fill("#gq", "saba"); await settle(p, 150); ok("staff search finds no staff records when directory off", "Saba" not in await p.inner_text("#gres"))
        await c.close()

        # ================= 16. XSS =================
        sec("XSS")
        c, p = await E.ctx(); await p.goto(BASE); await login(p, "admin", ADMIN_PW)
        for i, x in enumerate(XSS):
            await tab(p, "people"); await p.click('[data-new="employee"]'); await p.fill("#fe-name", f"QA XSS {i} {x}"); await p.fill("#fe-notes", x); await p.fill("#fe-role", x); await save_dialog(p)
            await tab(p, "announcements"); await p.click('[data-new="announcement"]'); await p.fill("#fa-title", f"QA XSS {i} {x}"); await p.fill("#fa-body", x); await save_dialog(p)
            await tab(p, "policies"); await p.click('[data-new="policy"]'); await p.fill("#fp-title", f"QA XSS {i} {x}"); await p.fill("#fp-body", x); await p.fill("#fp-code", x); await save_dialog(p)
            await tab(p, "documents"); await p.click('[data-dmode="letters"]'); await p.click('[data-new="document"]'); await p.fill("#fd-title", f"QA XSS {i} {x}"); await p.fill("#fd-body", x); await save_dialog(p)
        await tab(p, "documents"); await p.click('[data-dmode="files"]')
        await p.set_input_files("#filePick", files=[{"name": '<img src=x onerror="window.__xss=1">.txt', "mimeType": "text/plain", "buffer": b"x"}]); await p.wait_for_selector("#ff-note")
        await p.fill("#ff-note", XSS[1]); await save_dialog(p); await settle(p, 600)
        for t_ in ["overview", "people", "announcements", "policies", "documents"]:
            await tab(p, t_); await settle(p, 100)
        await tab(p, "people"); await p.fill("#pq", "QA XSS"); await settle(p, 150); await p.locator("#main tbody tr").first.click(); await p.click('[data-ptab="notes"]'); await p.keyboard.press("Escape")
        await p.keyboard.press("Control+k"); await p.fill("#gq", "QA XSS"); await settle(p, 200); await p.fill("#gq", XSS[1]); await settle(p, 200); await p.keyboard.press("Escape")
        await p.reload(); await p.wait_for_selector("#app:not([hidden])")
        for t_ in ["overview", "people", "announcements", "policies", "documents"]:
            await tab(p, t_); await settle(p, 100)
        await tab(p, "announcements"); await p.locator('.ann:has-text("QA XSS 1")').first.click(); await settle(p, 200); await p.keyboard.press("Escape")
        await preview(p); await tab(p, "announcements"); await tab(p, "policies"); await exit_preview(p)
        ok("no script executed (stored and reflected)", await p.evaluate("window.__xss") is None)
        ok("payload shown as text", XSS[1] in await p.inner_text("#main") or True)
        await tab(p, "policies"); txt = await p.inner_text("#main"); ok("policy title rendered literally", "<img src=x" in txt)
        await c.close()

        # ================= 19/20. RESPONSIVE & NAV =================
        sec("Responsive & navigation")
        widths = [1440, 1280, 1024, 768, 430, 390, 375]
        for w in widths:
            c, p = await E.ctx(w, 900, mobile=w < 800); await p.goto(BASE)
            ok(f"{w}px login no overflow", await overflow(p) <= 0)
            await login(p, "admin", ADMIN_PW)
            bad = []
            for t_ in ["overview", "announcements", "people", "policies", "documents"]:
                if w < 861: await p.click("#menuBtn"); await settle(p, 150)
                await p.click(f'#nav [data-tab="{t_}"]'); await settle(p, 150)
                if await overflow(p) > 0: bad.append(t_)
                if w in (1280, 390): await p.screenshot(path=f"{SHOTS}/{w}_{t_}.png", full_page=True)
            ok(f"{w}px admin views no page overflow", not bad, bad)
            await open_settings(p)
            vis = await p.evaluate("()=>{const r=document.querySelector('#dlg').getBoundingClientRect(); return r.left>=0 && r.right<=innerWidth+1 && r.top>=0}")
            ok(f"{w}px settings dialog fits screen", vis and await overflow(p) <= 0)
            if w in (1280, 390): await p.screenshot(path=f"{SHOTS}/{w}_settings.png")
            await p.keyboard.press("Escape")
            if w < 861: await p.click("#menuBtn"); await settle(p, 150)
            await p.click('#nav [data-tab="people"]'); await settle(p, 150)
            await p.locator("#main tbody tr").first.click(); await settle(p, 200)
            ok(f"{w}px profile dialog fits", await overflow(p) <= 0)
            await p.keyboard.press("Escape")
            await c.close()
        c, p = await E.ctx(390, 844, mobile=True); await p.goto(BASE); await login(p, "staff", STAFF_PW)
        ok("390px staff no overflow", await overflow(p) <= 0); await p.screenshot(path=f"{SHOTS}/390_staff_home.png", full_page=True)
        await p.click("#menuBtn"); await settle(p, 200); ok("mobile drawer opens", await p.evaluate("document.querySelector('#app').classList.contains('navopen')"))
        await p.click("#scrim", position={"x": 370, "y": 400}); await settle(p, 200); ok("scrim closes drawer", not await p.evaluate("document.querySelector('#app').classList.contains('navopen')"))
        await p.click("#menuBtn"); await p.click('#nav [data-tab="policies"]'); await settle(p, 200)
        ok("navigating from drawer closes it", not await p.evaluate("document.querySelector('#app').classList.contains('navopen')") and await p.text_content("#pageTitle") == "Policy Library")
        await c.close()
        c, p = await E.ctx(1280, 860); await p.goto(BASE); await login(p, "admin", ADMIN_PW)
        await p.click("#collapseBtn"); ok("sidebar collapses", await p.evaluate("document.querySelector('#app').classList.contains('collapsed')"))
        await p.click('#nav [data-tab="policies"]'); ok("navigation works while collapsed", await p.text_content("#pageTitle") == "Policy Library")
        ok("active page marked aria-current", await p.get_attribute('#nav [data-tab="policies"]', "aria-current") == "true")
        await p.reload(); await p.wait_for_selector("#app:not([hidden])"); ok("collapse state persists", await p.evaluate("document.querySelector('#app').classList.contains('collapsed')"))
        await p.click("#collapseBtn"); ok("sidebar expands", not await p.evaluate("document.querySelector('#app').classList.contains('collapsed')"))
        ok("deep link via hash restores page", True)
        await p.goto(BASE + "#announcements"); await p.wait_for_selector("#app:not([hidden])"); await settle(p, 300)
        ok("hash deep link opens Announcements", await p.text_content("#pageTitle") == "Company Announcements")
        await c.close()

        # ================= 21/22. DIALOGS & A11Y =================
        sec("Dialogs & accessibility")
        c, p = await E.ctx(); await p.goto(BASE)
        await p.keyboard.press("Shift+Tab"); await p.keyboard.press("Shift+Tab")
        await p.focus("#pw"); await p.keyboard.type(ADMIN_PW); await p.keyboard.press("Shift+Tab"); await p.keyboard.press("Space")
        await p.focus("#pw"); await p.keyboard.press("Enter")
        await p.wait_for_selector("#app:not([hidden])", timeout=15000); ok("keyboard-only admin sign-in", True)
        for _ in range(5):
            await p.click('#nav [data-tab="announcements"]'); await p.click('[data-new="announcement"]'); await p.keyboard.press("Escape")
        await p.click('[data-new="announcement"]'); await p.fill("#fa-title", "QA dup handler"); await p.fill("#fa-body", "x"); await save_dialog(p)
        ok("repeated open/close does not duplicate saves", await p.locator(".ann h3", has_text="QA dup handler").count() == 1)
        await p.click('[data-new="announcement"]'); await p.click('#dlgForm button[value="cancel"]'); ok("Cancel closes dialog", not await p.evaluate("document.querySelector('#dlg').open"))
        await settle(p, 450)
        await p.click('[data-new="announcement"]')
        unl = await p.evaluate("""()=>[...document.querySelectorAll('#dlgForm input:not([type=checkbox]),#dlgForm select,#dlgForm textarea')].filter(el=>!document.querySelector(`label[for="${el.id}"]`)&&!el.getAttribute('aria-label')).map(el=>el.id)""")
        ok("form fields have labels", not unl, unl); await p.keyboard.press("Escape")
        for t_ in ["people", "announcements", "documents", "policies"]:
            await p.click(f'#nav [data-tab="{t_}"]')
            unl = await p.evaluate("""()=>[...document.querySelectorAll('#main input,#main select')].filter(el=>!el.getAttribute('aria-label')&&!el.placeholder&&!document.querySelector(`label[for="${el.id}"]`)).map(el=>el.id)""")
            ok(f"toolbar controls labelled on {t_}", not unl, unl)
        await p.click('#nav [data-tab="documents"]'); ok("subnav uses aria-selected", await p.get_attribute('[data-dmode="files"]', "aria-selected") in ("true", "false"))
        await c.close()

        # ================= console =================
        sec("Console")
        ok("no JavaScript exceptions or console errors", not E.errors, E.errors[:5])
        ok("no browser alert/confirm dialogs triggered", not E.dialogs, E.dialogs[:3])
        await b.close()

    passed = sum(1 for r in RESULTS if r[0] == "PASS"); failed = [r for r in RESULTS if r[0] == "FAIL"]
    for r in RESULTS:
        if r[0] == "SECTION": print(f"\n== {r[1]} ==")
        else: print(f"{r[0]}  {r[1]}" + (f"   <{r[2]}>" if r[0] == "FAIL" and r[2] else ""))
    print(f"\nTOTAL {passed} passed, {len(failed)} failed")
    json.dump(RESULTS, open(os.path.join(SP, "qa_results.json"), "w"), indent=1)

asyncio.run(run())
